In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("../data/processed/bank_marketing_cleaned.csv")
df.head()

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,deposit
0,1.530858,0,1,1,0,0.908149,1,0,2,-1.265746,8,2.388642,-0.814270,-0.578658,-0.543848,3,1
1,1.273537,0,1,1,0,-0.794565,0,0,2,-1.265746,8,2.388642,-0.814270,-0.578658,-0.543848,3,1
2,-0.013067,9,1,1,0,0.113105,1,0,2,-1.265746,8,2.388642,-0.814270,-0.578658,-0.543848,3,1
3,1.187764,7,1,1,0,1.006696,1,0,2,-1.265746,8,0.793993,-0.814270,-0.578658,-0.543848,3,1
4,1.101990,0,1,2,0,-0.691572,0,0,2,-1.265746,8,1.124163,-0.156846,-0.578658,-0.543848,3,1

In [3]:
df.columns

Index(['age', 'job', 'marital', 'education', 'default', 'balance', 'housing',
       'loan', 'contact', 'day', 'month', 'duration', 'campaign', 'pdays',
       'previous', 'poutcome', 'deposit'],
      dtype='str')

In [4]:
df['interaction_score'] = df['campaign'] + df['previous']

df['avg_contact_intensity'] = df['duration'] / (df['campaign'] + 1)

In [5]:
df['balance_per_contact'] = df['balance'] / (df['campaign'] + 1)

In [6]:
# Lower pdays = more recent contact
df['recency_score'] = -df['pdays']

In [7]:
df.describe()

,age,job,marital,education,default,balance,housing,loan,contact,day,...,duration,campaign,pdays,previous,poutcome,deposit,interaction_score,avg_contact_intensity,balance_per_contact,recency_score
count,1.116200e+04,11162.000000,11162.000000,11162.000000,11162.000000,1.116200e+04,11162.000000,11162.000000,11162.000000,1.116200e+04,...,1.116200e+04,1.116200e+04,11162.000000,1.116200e+04,11162.000000,11162.000000,1.116200e+04,11162.000000,11162.000000,11162.000000
mean,2.699069e-16,4.487905,1.199337,1.285164,0.015051,-2.037033e-17,0.473123,0.130801,0.489697,-1.018517e-17,...,-8.148134e-17,-4.074067e-17,0.000000,-2.037033e-17,2.477782,0.473840,-3.564809e-17,-0.031808,0.052070,0.000000
std,1.000045e+00,3.225132,0.625552,0.749478,0.121761,1.000045e+00,0.499299,0.337198,0.818724,1.000045e+00,...,1.000045e+00,1.000045e+00,1.000045,1.000045e+00,1.002952,0.499338,1.331294e+00,3.356640,3.594478,1.000045
min,-1.985862e+00,0.000000,0.000000,0.000000,0.000000,-2.500242e+00,0.000000,0.000000,0.000000,-1.740784e+00,...,-1.232687e+00,-8.142698e-01,-0.578658,-5.438480e-01,0.000000,0.000000,-1.358118e+00,-6.636975,-13.461692,-1.738589
25%,-7.850303e-01,1.000000,1.000000,1.000000,0.000000,-7.375113e-01,0.000000,0.000000,0.000000,-9.094664e-01,...,-7.549943e-01,-8.142698e-01,-0.578658,-5.438480e-01,2.000000,0.000000,-1.358118e+00,-1.203713,-1.276025,-0.348241
50%,-1.846147e-01,4.000000,1.000000,1.000000,0.000000,-4.203827e-01,0.000000,0.000000,0.000000,-7.814820e-02,...,-3.440385e-01,-1.568463e-01,-0.578658,-5.438480e-01,3.000000,0.000000,-7.006944e-01,-0.322742,-0.334570,0.578658
75%,6.731219e-01,7.000000,2.000000,2.000000,0.000000,4.376428e-01,1.000000,0.000000,1.000000,7.531699e-01,...,5.024603e-01,5.005772e-01,0.348241,5.765712e-01,3.000000,1.000000,1.077148e+00,0.661509,0.604812,0.578658
max,2.860350e+00,11.000000,2.000000,3.000000,1.000000,2.200374e+00,1.000000,1.000000,2.000000,1.822008e+00,...,2.388642e+00,2.472848e+00,1.738589,2.257200e+00,3.000000,1.000000,4.730048e+00,12.860819,11.847154,0.578658

In [8]:
df.to_csv("../data/processed/bank_marketing_features.csv", index=False)

## Feature Engineering Summary

1. **Interaction Score**
   - Combines campaign and previous contact counts.
   - Represents overall marketing exposure of a customer.

2. **Average Contact Intensity**
   - Measures engagement effectiveness per contact.
   - Helps identify customers who respond better to fewer interactions.

3. **Balance per Contact**
   - Indicates customer financial value relative to marketing effort.

4. **Recency Score**
   - Derived from pdays to represent how recently the customer was contacted.
   - More recent interactions imply higher engagement potential.

These engineered features enhance customer behavior representation and improve clustering quality.